##################
## MultiSensors
##################
- platform: template
  sensors:
    multisensor1_motion:
      value_template: "{{ is_state('sensor.vision_security_zp3111_multisensor_4in1_burglar', '8') }}"
      friendly_name: "SrvRMMotion1"
      device_class: motion
      # entity_id: sensor.multisensor1_burglar

    multisensor1_tamper:
      value_template: "{{ is_state('sensor.vision_security_zp3111_multisensor_4in1_burglar', '3') }}"
      friendly_name: "SrvRMTamper1"
      device_class: safety
      # entity_id: sensor.multisensor1_burglar
    
    multisensor2_motion:
      value_template: "{{ is_state('sensor.vision_security_zp3111_multisensor_4in1_burglar_2', '8') }}"
      friendly_name: "OfficeMotion2"
      device_class: motion
      # entity_id: sensor.multisensor2_burglar

    multisensor2_tamper:
      value_template: "{{ is_state('sensor.vision_security_zp3111_multisensor_4in1_burglar_2', '3') }}"
      friendly_name: "OfficeTamper2"
      device_class: safety
      # entity_id: sensor.multisensor2_burglar

##################
## LeakSensors
##################
- platform: template
  sensors:
    flood_sensor1:
      value_template: "{{ is_state('sensor.everspring_st812_flood_detector_flood', '255') }}"
      friendly_name: "FloodSensor1"
      device_class: moisture
